### PR TITLE
[DEV-563] Manual deploy of CIM documentation site

### PR DESCRIPTION
**Pull request by zarakay**
# Description

This PR contains a manually generated CIM/Zepben Profile documentation site. The site hadn't been updated in a while so there are alot of changes. To test it, clone this repo and run `python3 -m http.server` in the root directory and view the server in the browser 

# Associated tasks

https://github.com/zepben/evolve-datamodel-site/pull/4

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [ ] ~I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
- [ ] ~I have commented my code in any hard-to-understand or hacky areas.~
- [ ] ~I have handled all new warnings generated by the compiler or IDE.~
- [x] I have rebased onto the target branch (usually main).
      
### Documentation
- [ ] ~I have updated the changelog.~
- [ ] ~I have updated any documentation required for these changes.~

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [DEV-563 Deploy updated CIM site](https://app.clickup.com/t/6929263/DEV-563)

**Comment by kgreav** [comment]
TransformerCoolingType seems to have picked up VectorGroups description and fields.

Also noticed an existing issue with enums in that the attribute tables have 3 columns -  Name, Type, Description.
Enums should probably just have Name, Description - dunno how easy that is but if it is may as well update it now.

Attributes for Terminal in the evolve profile are also broken - ye better have a look to figure that one out...
DiagramObjectPoint, EquivalentBranch, EnergySource, PowerTransformerEnd, RatioTapChanger, RegulatingControl, SeriesCompensator, TapChanger also looks broken in a similar way. Looks like this also occurs in the CIM100 - example can be seen in ACDCTerminal

EnergyConsumer is broken in a different and worse way - looks like some broken 

Ground in the Evolve profile has an association to GroundAction which isn't in the evolve profile.

Class description for Circuit is "null" - probably should just be blank.

Note I didn't go over everything - this was just spot checking with the intent on hopefully capturing all the issues.

**Review by kgreav — CHANGES_REQUESTED** [review]
some comment

**Comment by zarakay** [comment]
- TransformerCoolingType was my mistake, copy pasta - its now fixed
- The rest were because there were new lines and | characters that broke the markdown. This has now been fixed.
- We can't do the enum one since we don't know when something is an enum. Maybe some follow up work to add an attribute

**Pull request merged**
