### PR TITLE
[DEV-793] Deploy CIM site with new data-model and rename

### PR DESCRIPTION
**Pull request by zarakay**
# Description

As titled

# Associated tasks

- Spec updates - https://github.com/zepben/ewb-grpc/pull/101
- Markdown updates - https://github.com/zepben/evolve-datamodel-site/pull/5

# Checklist

No checklist since its just autogenerated stuff

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [DEV-793 Update profile / website doco](https://app.clickup.com/t/6929263/DEV-793)

**Review by josh-leyshon — APPROVED** [review]
My browser chugs so hard trying to load the files changed 😭 I'm assuming this is all just generated though from https://github.com/zepben/evolve-datamodel-site/pull/5 ? If so then no problems here.

**Comment by josh-leyshon** [comment]
Me trying to review this PR (realtime don't actually watch it all it's boring)

https://github.com/zepben/zepben.github.io/assets/45578963/ddb4967f-92fd-4f7e-8c31-9f3f9e1d52a4

**Comment by zarakay** [comment]
@josh-leyshon yes lol the PR is all autogenerated from the linked docs site. Just manual since we don't have any automation in place just yet

**Pull request merged**
